import { EmergencyType, Severity, FirstAidStep, MedicineSuggestion } from '../../types';

/**
 * A structured clinical protocol for one emergency category.
 * Drives both the rule-based fallback engine and post-processing of Gemini output.
 */
export interface EmergencyProtocol {
  type: EmergencyType;
  label: string;
  /** Weighted keyword/phrases. Higher weight => stronger, more specific signal. */
  signals: { term: string; weight: number }[];
  baseSeverity: Severity;
  conditions: { condition: string; probability: number }[];
  /** Prioritized recommended actions (index 0 == highest priority). */
  actions: string[];
  firstAid: string[];
  redFlags: string[];
  /** Vetted OTC / self-care medicine suggestions (or explicit "avoid" warnings). */
  medicines: MedicineSuggestion[];
  hospitalRequired: boolean;
  ambulanceRequired: boolean;
}

export const PROTOCOLS: EmergencyProtocol[] = [
  {
    type: 'cardiac',
    label: 'Possible Cardiac Event',
    signals: [
      { term: 'chest pain', weight: 5 },
      { term: 'chest tightness', weight: 5 },
      { term: 'chest pressure', weight: 5 },
      { term: 'heart attack', weight: 6 },
      { term: 'pain in left arm', weight: 4 },
      { term: 'left arm', weight: 3 },
      { term: 'jaw pain', weight: 3 },
      { term: 'palpitations', weight: 3 },
      { term: 'sweating', weight: 2 },
      { term: 'cold sweat', weight: 3 },
      { term: 'shortness of breath', weight: 3 },
      { term: 'heart racing', weight: 3 },
    ],
    baseSeverity: 'critical',
    conditions: [
      { condition: 'Acute coronary syndrome / heart attack', probability: 0.55 },
      { condition: 'Angina', probability: 0.25 },
      { condition: 'Panic attack', probability: 0.12 },
      { condition: 'Musculoskeletal chest pain', probability: 0.08 },
    ],
    actions: [
      'Call emergency services (108/112) now — treat as a heart attack until proven otherwise',
      'Have the person sit down, stay calm, and rest in a half-sitting position',
      'Loosen tight clothing and keep them warm',
      'If prescribed, help them take their own nitroglycerin',
      'If not allergic and advised by a dispatcher, chew one adult aspirin (300 mg)',
      'Be ready to start CPR if they become unresponsive and stop breathing normally',
    ],
    firstAid: [
      'Keep the person calm and seated in a half-upright position.',
      'Loosen any tight clothing around the neck and chest.',
      'Ask if they take heart medication (e.g., nitroglycerin) and help them use their own.',
      'If they are unconscious and not breathing normally, begin hands-only CPR: push hard and fast in the centre of the chest (100–120/min).',
      'Do not give food or water. Stay with them until help arrives.',
    ],
    redFlags: [
      'Loss of consciousness',
      'No pulse or not breathing normally',
      'Crushing chest pain spreading to arm, jaw, or back',
      'Bluish lips or face',
    ],
    medicines: [
      {
        name: 'Aspirin (Disprin / Ecosprin)',
        purpose: 'Helps thin the blood during a suspected heart attack',
        dosage: 'One 300 mg tablet, chewed slowly — once only',
        caution: 'Only if the person is conscious, is not allergic to aspirin, and after calling 108. Never delay the ambulance to look for it.',
        category: 'otc',
      },
      {
        name: 'Nitroglycerin / Sorbitrate (under the tongue)',
        purpose: 'Eases chest pain in known heart patients',
        dosage: 'The person’s own prescribed dose',
        caution: 'Only if it was already prescribed to this person — never give someone else’s.',
        category: 'prescription',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: true,
  },
  {
    type: 'neurological',
    label: 'Possible Stroke / Neurological Emergency',
    signals: [
      { term: 'stroke', weight: 6 },
      { term: 'face drooping', weight: 5 },
      { term: 'slurred speech', weight: 5 },
      { term: 'cannot speak', weight: 4 },
      { term: 'numbness', weight: 3 },
      { term: 'one side', weight: 4 },
      { term: 'weakness on one side', weight: 5 },
      { term: 'sudden confusion', weight: 4 },
      { term: 'seizure', weight: 6 },
      { term: 'convulsions', weight: 5 },
      { term: 'fainting', weight: 2 },
      { term: 'worst headache', weight: 4 },
      { term: 'blurred vision', weight: 2 },
      { term: 'loss of balance', weight: 3 },
    ],
    baseSeverity: 'critical',
    conditions: [
      { condition: 'Stroke (ischemic or hemorrhagic)', probability: 0.5 },
      { condition: 'Seizure disorder', probability: 0.22 },
      { condition: 'Transient ischemic attack (TIA)', probability: 0.18 },
      { condition: 'Severe migraine', probability: 0.1 },
    ],
    actions: [
      'Call emergency services (108/112) immediately — note the time symptoms started',
      'Use the FAST check: Face drooping, Arm weakness, Speech difficulty, Time to call',
      'Keep the person lying on their side with head slightly raised',
      'Do not give food, drink, or medication',
      'For a seizure: clear the area, cushion the head, do NOT restrain or put anything in the mouth',
    ],
    firstAid: [
      'Note the exact time symptoms began — this is critical for treatment.',
      'Help the person lie down on their side (recovery position) with head and shoulders slightly raised.',
      'Do not give anything to eat or drink.',
      'During a seizure: move objects away, cushion the head, and time the seizure. Never restrain them or put anything in their mouth.',
      'After a seizure, place them in the recovery position and stay until help arrives.',
    ],
    redFlags: [
      'Sudden weakness or numbness on one side',
      'Slurred speech or inability to speak',
      'Seizure lasting more than 5 minutes or repeated seizures',
      'Unresponsiveness after the episode',
    ],
    medicines: [
      {
        name: 'No tablets, food, or water by mouth',
        purpose: 'Anything swallowed can cause choking during a stroke or seizure',
        caution: 'Do not give aspirin or any medicine. Note the time symptoms started and call 108 immediately.',
        category: 'avoid',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: true,
  },
  {
    type: 'respiratory',
    label: 'Breathing Emergency',
    signals: [
      { term: 'not breathing', weight: 6 },
      { term: 'cannot breathe', weight: 6 },
      { term: "can't breathe", weight: 6 },
      { term: 'difficulty breathing', weight: 5 },
      { term: 'shortness of breath', weight: 4 },
      { term: 'choking', weight: 6 },
      { term: 'wheezing', weight: 3 },
      { term: 'asthma', weight: 4 },
      { term: 'gasping', weight: 4 },
      { term: 'blue lips', weight: 5 },
      { term: 'suffocating', weight: 5 },
    ],
    baseSeverity: 'critical',
    conditions: [
      { condition: 'Severe asthma attack', probability: 0.35 },
      { condition: 'Airway obstruction / choking', probability: 0.3 },
      { condition: 'Anaphylaxis', probability: 0.2 },
      { condition: 'Respiratory infection / pneumonia', probability: 0.15 },
    ],
    actions: [
      'Call emergency services (108/112) if breathing is severely laboured or stopping',
      'Sit the person upright to ease breathing',
      'For choking (unable to speak/cough): give 5 back blows then 5 abdominal thrusts (Heimlich)',
      'Help them use their own reliever inhaler (asthma) if available',
      'Keep them calm — panic worsens breathlessness',
    ],
    firstAid: [
      'Sit the person upright and encourage slow, steady breaths.',
      'If choking and they cannot cough or speak: lean them forward and give 5 firm back blows between the shoulder blades, then 5 abdominal thrusts. Repeat until clear.',
      'For asthma: help them take their reliever (blue) inhaler — one puff every 30–60 seconds, up to 10 puffs.',
      'Loosen tight clothing around the neck and chest.',
      'If they stop breathing, begin CPR and call emergency services immediately.',
    ],
    redFlags: [
      'Lips or face turning blue',
      'Unable to speak or cough',
      'Breathing stops or becomes very shallow',
      'Drowsiness or loss of consciousness',
    ],
    medicines: [
      {
        name: 'Salbutamol reliever inhaler (Asthalin — blue inhaler)',
        purpose: 'Opens the airways during an asthma attack',
        dosage: 'One puff every 30–60 seconds, up to 10 puffs',
        caution: 'Only for a known asthmatic using their own inhaler. If there is no relief, call 108.',
        category: 'prescription',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: true,
  },
  {
    type: 'bleeding',
    label: 'Severe Bleeding',
    signals: [
      { term: 'severe bleeding', weight: 6 },
      { term: 'heavy bleeding', weight: 6 },
      { term: 'bleeding heavily', weight: 6 },
      { term: 'blood everywhere', weight: 4 },
      { term: 'wont stop bleeding', weight: 5 },
      { term: "won't stop bleeding", weight: 5 },
      { term: 'gushing blood', weight: 5 },
      { term: 'deep cut', weight: 4 },
      { term: 'laceration', weight: 3 },
      { term: 'stab', weight: 5 },
      { term: 'gunshot', weight: 6 },
      { term: 'amputation', weight: 6 },
    ],
    baseSeverity: 'critical',
    conditions: [
      { condition: 'Major haemorrhage', probability: 0.5 },
      { condition: 'Arterial bleed', probability: 0.25 },
      { condition: 'Deep laceration', probability: 0.25 },
    ],
    actions: [
      'Call emergency services (108/112) for heavy or uncontrolled bleeding',
      'Apply firm, direct pressure on the wound with a clean cloth',
      'Keep pressure continuous — do not lift to check',
      'Raise the injured area above heart level if possible',
      'Lay the person down to reduce shock; keep them warm',
    ],
    firstAid: [
      'Apply firm, direct pressure to the wound using a clean cloth or dressing.',
      'If blood soaks through, add more cloth on top — do not remove the first layer.',
      'Raise the injured limb above the level of the heart if no fracture is suspected.',
      'Lay the person down and keep them warm to reduce the risk of shock.',
      'Do not remove any embedded object — press around it instead.',
    ],
    redFlags: [
      'Blood spurting or not slowing with pressure',
      'Pale, cold, clammy skin (shock)',
      'Confusion or fainting',
      'An embedded object or amputated part',
    ],
    medicines: [
      {
        name: 'Avoid aspirin & ibuprofen',
        purpose: 'These thin the blood and can make bleeding worse',
        caution: 'Do not give blood-thinning painkillers. Apply firm, direct pressure and call 108.',
        category: 'avoid',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: true,
  },
  {
    type: 'allergic',
    label: 'Allergic Reaction / Anaphylaxis',
    signals: [
      { term: 'anaphylaxis', weight: 6 },
      { term: 'allergic reaction', weight: 5 },
      { term: 'swollen throat', weight: 5 },
      { term: 'swelling of face', weight: 4 },
      { term: 'swelling lips', weight: 4 },
      { term: 'hives', weight: 3 },
      { term: 'rash spreading', weight: 3 },
      { term: 'bee sting', weight: 3 },
      { term: 'peanut', weight: 3 },
      { term: 'epipen', weight: 4 },
      { term: 'throat closing', weight: 5 },
    ],
    baseSeverity: 'critical',
    conditions: [
      { condition: 'Anaphylaxis', probability: 0.5 },
      { condition: 'Moderate allergic reaction', probability: 0.3 },
      { condition: 'Localised allergic reaction', probability: 0.2 },
    ],
    actions: [
      'Call emergency services (108/112) if there is throat swelling or breathing difficulty',
      'Use an adrenaline auto-injector (EpiPen) immediately if available — outer thigh',
      'Help the person sit up if breathing is hard; lay flat and raise legs if faint',
      'Remove the trigger if known (e.g., stinger)',
      'Be ready to give a second EpiPen after 5 minutes if no improvement',
    ],
    firstAid: [
      'If an adrenaline auto-injector (EpiPen) is available, use it right away in the outer thigh.',
      'Call emergency services and tell them it is a suspected anaphylaxis.',
      'Help the person into a position that eases breathing; if faint, lay them flat and raise their legs.',
      'Loosen tight clothing and keep them calm and still.',
      'If symptoms return or do not improve within 5 minutes, use a second auto-injector if available.',
    ],
    redFlags: [
      'Swelling of the tongue, throat, or lips',
      'Difficulty breathing or noisy breathing',
      'Dizziness, collapse, or fainting',
      'Widespread hives with breathing trouble',
    ],
    medicines: [
      {
        name: 'Adrenaline auto-injector (EpiPen)',
        purpose: 'First-line treatment for a severe allergic reaction (anaphylaxis)',
        dosage: 'Inject into the outer thigh; a second dose after 5 minutes if no improvement',
        caution: 'Use the person’s own auto-injector right away, then call 108.',
        category: 'prescription',
      },
      {
        name: 'Antihistamine (Cetirizine / Levocetirizine)',
        purpose: 'Eases mild reactions such as itching, hives, and sneezing',
        dosage: 'One tablet (Cetirizine 10 mg)',
        caution: 'For mild reactions only — it does NOT treat throat swelling or breathing trouble. Use adrenaline for those.',
        category: 'otc',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: true,
  },
  {
    type: 'poisoning',
    label: 'Poisoning / Overdose',
    signals: [
      { term: 'poison', weight: 5 },
      { term: 'overdose', weight: 6 },
      { term: 'swallowed', weight: 3 },
      { term: 'ingested', weight: 3 },
      { term: 'took too many pills', weight: 5 },
      { term: 'chemical', weight: 3 },
      { term: 'drank bleach', weight: 5 },
      { term: 'carbon monoxide', weight: 5 },
      { term: 'venom', weight: 3 },
      { term: 'snake bite', weight: 5 },
    ],
    baseSeverity: 'urgent',
    conditions: [
      { condition: 'Toxic ingestion / poisoning', probability: 0.45 },
      { condition: 'Medication overdose', probability: 0.3 },
      { condition: 'Chemical exposure', probability: 0.25 },
    ],
    actions: [
      'Call emergency services (108/112) or Poison Control (1066 in India)',
      'Identify the substance and how much/when if possible — keep the container',
      'Do NOT induce vomiting unless explicitly told to by a professional',
      'If unconscious but breathing, place in the recovery position',
      'Move to fresh air for inhaled poisons (e.g., carbon monoxide)',
    ],
    firstAid: [
      'Call Poison Control (1066) or emergency services and follow their exact instructions.',
      'Try to identify the substance, amount, and time — keep packaging or a sample.',
      'Do not make the person vomit unless a professional tells you to.',
      'For skin/eye contact, rinse with plenty of running water.',
      'If they are unconscious but breathing, place them in the recovery position and monitor.',
    ],
    redFlags: [
      'Unconsciousness or seizures',
      'Difficulty breathing',
      'Burns around the mouth (corrosive substance)',
      'Known large overdose',
    ],
    medicines: [
      {
        name: 'Do not give any antidote or induce vomiting',
        purpose: 'Home remedies like salt water or milk can cause more harm',
        caution: 'Call Poison Control (1066) or 108 and follow their exact instructions. Keep the container or pills to show responders.',
        category: 'avoid',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: true,
  },
  {
    type: 'burn',
    label: 'Burn Injury',
    signals: [
      { term: 'burn', weight: 4 },
      { term: 'burned', weight: 4 },
      { term: 'scald', weight: 4 },
      { term: 'boiling water', weight: 3 },
      { term: 'fire', weight: 3 },
      { term: 'electric shock', weight: 5 },
      { term: 'chemical burn', weight: 5 },
      { term: 'blistering', weight: 3 },
    ],
    baseSeverity: 'urgent',
    conditions: [
      { condition: 'Thermal burn', probability: 0.5 },
      { condition: 'Scald', probability: 0.25 },
      { condition: 'Chemical or electrical burn', probability: 0.25 },
    ],
    actions: [
      'Cool the burn under cool (not ice-cold) running water for at least 20 minutes',
      'Remove jewellery/clothing near the burn unless stuck to the skin',
      'Cover loosely with cling film or a clean, non-fluffy cloth',
      'Do not apply creams, butter, or ice',
      'Seek emergency care for large, deep, facial, or electrical/chemical burns',
    ],
    firstAid: [
      'Move away from the source of the burn and stop the burning process.',
      'Cool the burn under cool running water for at least 20 minutes.',
      'Remove watches, rings, or tight clothing near the area before it swells (unless stuck).',
      'Cover the burn loosely with cling film or a clean, lint-free cloth.',
      'Do not burst blisters or apply butter, toothpaste, or ice.',
    ],
    redFlags: [
      'Burn larger than the person’s palm',
      'Burns to the face, hands, feet, or genitals',
      'Deep, white, or charred skin',
      'Electrical or chemical burns',
    ],
    medicines: [
      {
        name: 'Paracetamol (Crocin / Dolo)',
        purpose: 'Relieves burn pain',
        dosage: '500–1000 mg, up to every 6 hours (maximum 4 g in 24 hours)',
        caution: 'Cool the burn under running water first. Do not apply any cream, toothpaste, or ointment to the burn.',
        category: 'otc',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: false,
  },
  {
    type: 'trauma',
    label: 'Injury / Trauma',
    signals: [
      { term: 'fracture', weight: 4 },
      { term: 'broken bone', weight: 4 },
      { term: 'broken arm', weight: 4 },
      { term: 'broken leg', weight: 4 },
      { term: 'fell', weight: 2 },
      { term: 'fall', weight: 2 },
      { term: 'accident', weight: 3 },
      { term: 'car crash', weight: 5 },
      { term: 'head injury', weight: 5 },
      { term: 'hit his head', weight: 4 },
      { term: 'dislocated', weight: 3 },
      { term: 'sprain', weight: 2 },
      { term: 'neck injury', weight: 5 },
    ],
    baseSeverity: 'urgent',
    conditions: [
      { condition: 'Fracture or dislocation', probability: 0.4 },
      { condition: 'Head injury / concussion', probability: 0.3 },
      { condition: 'Soft-tissue injury (sprain/strain)', probability: 0.3 },
    ],
    actions: [
      'Call emergency services for head, neck, spine injuries or major trauma',
      'Keep the person still — do not move them if a spinal injury is suspected',
      'Support and immobilise the injured area; do not try to realign bones',
      'Apply a cold pack wrapped in cloth to reduce swelling',
      'Watch for drowsiness, vomiting, or confusion after a head injury',
    ],
    firstAid: [
      'Keep the injured person still and reassure them.',
      'For a suspected fracture, support the limb in the position found — do not straighten it.',
      'Apply a cold pack wrapped in a cloth for up to 20 minutes to limit swelling.',
      'For head injuries, monitor consciousness and watch for vomiting or confusion.',
      'Do not move anyone with a suspected neck or spine injury unless they are in danger.',
    ],
    redFlags: [
      'Loss of consciousness after a head injury',
      'Repeated vomiting or seizures',
      'Bone visible through the skin or severe deformity',
      'Numbness/tingling suggesting a spinal injury',
    ],
    medicines: [
      {
        name: 'Paracetamol (Crocin / Dolo)',
        purpose: 'Preferred pain relief after an injury',
        dosage: '500–1000 mg, up to every 6 hours (maximum 4 g in 24 hours)',
        caution: 'Avoid aspirin or ibuprofen if there is heavy bleeding or a serious injury — they can increase bleeding.',
        category: 'otc',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: false,
  },
  {
    type: 'heat',
    label: 'Heat-Related Illness',
    signals: [
      { term: 'heat stroke', weight: 6 },
      { term: 'heatstroke', weight: 6 },
      { term: 'heat exhaustion', weight: 5 },
      { term: 'overheating', weight: 3 },
      { term: 'very hot skin', weight: 3 },
      { term: 'dehydration', weight: 3 },
      { term: 'collapsed in the heat', weight: 5 },
    ],
    baseSeverity: 'urgent',
    conditions: [
      { condition: 'Heat stroke', probability: 0.45 },
      { condition: 'Heat exhaustion', probability: 0.4 },
      { condition: 'Dehydration', probability: 0.15 },
    ],
    actions: [
      'Call emergency services if the person is confused, unconscious, or has very hot dry skin',
      'Move them to a cool, shaded place immediately',
      'Remove excess clothing and cool the skin with water and fanning',
      'If fully alert, give small sips of water',
      'Apply cold packs to the neck, armpits, and groin',
    ],
    firstAid: [
      'Move the person to a cool, shaded, or air-conditioned area.',
      'Remove outer clothing and cool their skin with wet cloths or a sponge while fanning.',
      'Place cold packs on the neck, armpits, and groin.',
      'If they are fully conscious, give small sips of cool water.',
      'If they are confused, vomiting, or unconscious, treat as heat stroke and call for help.',
    ],
    redFlags: [
      'Confusion, agitation, or seizures',
      'Hot, dry skin with a high body temperature',
      'Loss of consciousness',
      'No improvement after 30 minutes of cooling',
    ],
    medicines: [
      {
        name: 'Oral Rehydration Salts (ORS)',
        purpose: 'Replaces water and salts lost through heat',
        dosage: 'Sip one glass slowly if fully conscious',
        caution: 'Do not give fluids to someone who is confused or unconscious. Fever tablets like paracetamol do NOT help heat stroke.',
        category: 'otc',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: false,
  },
  {
    type: 'diabetic',
    label: 'Diabetic Emergency',
    signals: [
      { term: 'diabetic', weight: 4 },
      { term: 'low blood sugar', weight: 5 },
      { term: 'hypoglycemia', weight: 5 },
      { term: 'high blood sugar', weight: 4 },
      { term: 'hyperglycemia', weight: 4 },
      { term: 'shaky and sweaty', weight: 3 },
      { term: 'insulin', weight: 3 },
      { term: 'confused and sweating', weight: 3 },
    ],
    baseSeverity: 'urgent',
    conditions: [
      { condition: 'Hypoglycaemia (low blood sugar)', probability: 0.5 },
      { condition: 'Hyperglycaemia (high blood sugar)', probability: 0.35 },
      { condition: 'Diabetic ketoacidosis', probability: 0.15 },
    ],
    actions: [
      'If conscious and able to swallow, give a sugary drink or glucose (for low blood sugar)',
      'Call emergency services if unconscious or not improving',
      'Do not give anything by mouth to an unconscious person',
      'If unconscious but breathing, place in the recovery position',
      'Recheck after 10–15 minutes and repeat sugar if still unwell',
    ],
    firstAid: [
      'If the person is conscious and can swallow, give a sugary drink, glucose tablets, or sweets.',
      'Let them rest and recheck after 10–15 minutes; repeat sugar if needed.',
      'Do not give food or drink to someone who is drowsy or unconscious.',
      'If unconscious but breathing, place them in the recovery position.',
      'Call emergency services if they do not improve quickly or lose consciousness.',
    ],
    redFlags: [
      'Unconsciousness or unresponsiveness',
      'Seizures',
      'Rapid, deep breathing with a fruity breath smell',
      'No improvement after giving sugar',
    ],
    medicines: [
      {
        name: 'Glucose tablets, sugar, or fruit juice',
        purpose: 'Quickly raises dangerously low blood sugar',
        dosage: '15–20 g of fast-acting sugar; recheck after 15 minutes and repeat if still unwell',
        caution: 'Only if the person is conscious and able to swallow. Never give sugar by mouth to an unconscious person.',
        category: 'otc',
      },
    ],
    hospitalRequired: true,
    ambulanceRequired: false,
  },
  {
    type: 'general',
    label: 'General Medical Concern',
    signals: [
      { term: 'fever', weight: 2 },
      { term: 'headache', weight: 1 },
      { term: 'pain', weight: 1 },
      { term: 'vomiting', weight: 2 },
      { term: 'dizzy', weight: 2 },
      { term: 'nausea', weight: 1 },
      { term: 'cough', weight: 1 },
      { term: 'sore throat', weight: 1 },
    ],
    baseSeverity: 'moderate',
    conditions: [
      { condition: 'Viral illness', probability: 0.4 },
      { condition: 'Minor infection', probability: 0.3 },
      { condition: 'Non-specific symptoms', probability: 0.3 },
    ],
    actions: [
      'Monitor symptoms and rest; stay hydrated',
      'Take temperature and note any changes',
      'Contact a doctor or telehealth service if symptoms persist or worsen',
      'Seek urgent care if new red-flag symptoms appear',
      'Keep a record of when symptoms started',
    ],
    firstAid: [
      'Rest and keep hydrated with water or oral rehydration fluids.',
      'Use a thermometer to monitor fever and note any changes.',
      'Manage mild pain or fever with over-the-counter medication as directed on the label.',
      'Watch for warning signs like breathing difficulty, severe pain, or confusion.',
      'Contact a healthcare provider if symptoms persist beyond a couple of days or worsen.',
    ],
    redFlags: [
      'Difficulty breathing',
      'Severe or worsening pain',
      'High fever that does not respond to medication',
      'Confusion, stiff neck, or a spreading rash',
    ],
    medicines: [
      {
        name: 'Paracetamol (Crocin / Dolo)',
        purpose: 'Reduces fever and eases mild pain',
        dosage: '500–1000 mg, up to every 6 hours (maximum 4 g in 24 hours)',
        caution: 'Follow the label. See a doctor if fever lasts more than 3 days or symptoms get worse.',
        category: 'otc',
      },
      {
        name: 'Oral Rehydration Salts (ORS)',
        purpose: 'Prevents dehydration from fever, vomiting, or diarrhoea',
        dosage: 'Sip through the day',
        caution: 'Seek care if you cannot keep fluids down.',
        category: 'otc',
      },
    ],
    hospitalRequired: false,
    ambulanceRequired: false,
  },
];

export const getProtocol = (type: EmergencyType): EmergencyProtocol => {
  return PROTOCOLS.find((p) => p.type === type) ?? (PROTOCOLS[PROTOCOLS.length - 1] as EmergencyProtocol);
};

export const toFirstAidSteps = (steps: string[]): FirstAidStep[] =>
  steps.map((instruction, i) => ({ step: i + 1, instruction }));
